### ISSUE TITLE
Double scrollbars

### ISSUE THREAD

**Issue by Rataxes** [iamjpg/Ez-Background-Resize#2]
I get double scrollbars in IE7 unless I put overflow:hidden in css

**Comment by iamjpg** [comment]
That's interesting.  I can't reproduce this.  It works for me.  Could you post your implementation so I can take a look in IE7?  Thanks.

**Comment by iamjpg** [comment]
Closing due to inability to replicate.

**Comment by hayesgm** [comment]
I recently witnessed this error on IE8.  I believe my IE8 compatibility fix (see pull requests) solved the issue for my client.
